#!/usr/bin/bash
clear=$'\033[2J'
top=$'\033[H'

trap "setterm --cursor on; echo ${clear}; exit; trap -- - SIGINT SIGTERM" SIGTERM SIGINT

seconds="$1"
echo "${clear}"

start="$(($(date +%s) + $seconds))"
while [ "$start" -ge `date +%s` ]; do
  time="$(( $start - `date +%s` ))"
  echo "${top}"
  what="$(date -u -d "@$time" +%H:%M:%S)"
  figlet <<<"$what" | lolcat
  setterm --cursor off
  sleep 1
  echo "${clear}"
done

printf "REST IS OVER!! - BACK TO HACKING!!" | cowsay | lolcat
