#!/usr/bin/bash

# Actualizacion completa del sistema
sudo apt update && sudo apt upgrade -y

# Instalacion completa de todas las herramientas
sudo apt install -y vim tmux neofetch torsocks proxychains \
        nyx gowitness jq shellcheck yt-dlp subfinder httpx-toolkit podman \
        zaproxy keepassxc flameshot chromium i2pd torbrowser-launcher tor \
        golang-go chromium

# Instalacion de herramientas de go
go install github.com/sensepost/gowitness@latest                                                                                                                             
                                                                                                                                                                             
# Instalacion de zeronet                                                                                                                                                     
podman pull docker.io/nofish/zeronet

# Instalacion de freenet
cd /tmp/
wget 'https://www.draketo.de/dateien/freenet/build01496/new_installer_offline_1496.jar' -O new_installer_offline.jar
java -jar new_installer_offline.jar
